version: "3.8"

name: lab-football-coach

services:
  db:
    image: postgres:12-alpine
    container_name: database
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "54325:5432"
    volumes:
      - sensedia_challenge_api_data:/var/lib/postgresql/data

volumes:
  sensedia_challenge_api_data:
